In [3]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

df = pd.DataFrame({
    "Education": ["High School", "Graduate", "Postgraduate", "Graduate", "High School"]
})

print("Original Data:")
display(df)

encoder = OrdinalEncoder(categories=[["High School", "Graduate", "Postgraduate"]])

df["Education_Encoded"] = encoder.fit_transform(df[["Education"]])

print("\nEncoded Data:")
display(df)

Original Data:

      Education
0   High School
1      Graduate
2  Postgraduate
3      Graduate
4   High School

Encoded Data:

      Education  Education_Encoded
0   High School                0.0
1      Graduate                1.0
2  Postgraduate                2.0
3      Graduate                1.0
4   High School                0.0

In [4]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

df = pd.DataFrame({
    "City": ["Delhi", "Mumbai", "Chennai", "Kolkata", "Delhi"]
})

print("Original Data:")
display(df)

le = LabelEncoder()

df["City_Encoded"] = le.fit_transform(df["City"])

print("\nEncoded Data:")
display(df)

decoded = le.inverse_transform(df["City_Encoded"])

print("\nDecoded Values:")
display(decoded)

Original Data:

      City
0    Delhi
1   Mumbai
2  Chennai
3  Kolkata
4    Delhi

Encoded Data:

      City  City_Encoded
0    Delhi             1
1   Mumbai             3
2  Chennai             0
3  Kolkata             2
4    Delhi             1

Decoded Values:

array(['Delhi', 'Mumbai', 'Chennai', 'Kolkata', 'Delhi'], dtype=object)

In [6]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({
    "Department": ["HR", "IT", "Finance", "Sales", "HR"]
})

print("Original Data:")
print(df)

encoded = pd.get_dummies(df, columns=["Department"])

print("\nEncoded Data:")
display(encoded)


df = pd.DataFrame({
    "Department": ["HR", "IT", "Finance", "Sales", "HR"]
})

print("Original Data:")
display(df)

ohe = OneHotEncoder(
    sparse_output=False,
    handle_unknown="ignore"
)

encoded = ohe.fit_transform(df[["Department"]])

encoded_df = pd.DataFrame(
    encoded,
    columns=ohe.get_feature_names_out(["Department"])
)

print("\nEncoded Data:")
display(encoded_df)

Original Data:
  Department
0         HR
1         IT
2    Finance
3      Sales
4         HR

Encoded Data:

   Department_Finance  Department_HR  Department_IT  Department_Sales
0               False           True          False             False
1               False          False           True             False
2                True          False          False             False
3               False          False          False              True
4               False           True          False             False

Original Data:

  Department
0         HR
1         IT
2    Finance
3      Sales
4         HR

Encoded Data:

   Department_Finance  Department_HR  Department_IT  Department_Sales
0                 0.0            1.0            0.0               0.0
1                 0.0            0.0            1.0               0.0
2                 1.0            0.0            0.0               0.0
3                 0.0            0.0            0.0               1.0
4                 0.0            1.0            0.0               0.0