# Part - A

1. What is data analysis?
- Data analysis is the process of inspecting, cleaning, transforming, and modeling data with the goal of discovering useful information, drawing conclusions, and supporting decision-making. It involves various techniques and tools to analyze data sets and extract meaningful insights.

2. how to plan data science projects?
- Planning data science projects involves several key steps:
   - Define the problem.
   - Collect and understand data.
   - Data preprocessing.
   - Exploratory data analysis (EDA).
   - Feature engineering.
   - Model selection.
   - Model training and evaluation.
   - Deployment.
   - Monitoring and maintenance.

3. How to frame machine learning problems?
- Framing machine learning problems involves several steps:
   - Define the objective.
   - Identify the type of problem.
   - Specify the input and output.
   - Determine evaluation metrics.
   - Consider constraints and limitations.
   - Formulate hypotheses.

4. Explain Tensors and provide an in-depth explanation with numpy examples.
- Tensors are multi-dimensional arrays that generalize the concept of scalars, vectors, and matrices. They are a fundamental data structure in machine learning and deep learning frameworks like TensorFlow and PyTorch. Tensors can have any number of dimensions, making them suitable for representing complex data structures.
In NumPy, tensors can be represented using the `numpy.ndarray` class. Here are some examples:

```python
import numpy as np

scalar = np.array(5)
print(scalar)  
print(scalar.ndim)  

vector = np.array([1, 2, 3])
print(vector)  
print(vector.ndim)  

matrix = np.array([[1, 2], [3, 4]])
print(matrix)  
print(matrix.ndim)  


tensor_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor_3d)
print(tensor_3d.ndim)  
```

# Part - B

In [1]:
import pandas as pd
import json
import requests


df = pd.read_csv(r'D:\RW\RW_Exam\Data_Preprocecing\Final_project\data\customer_credit_risk_dataset.csv')
display(df.head())


with open("data/customer_metadata.json", "r") as file:
    metadata = json.load(file)

metadata_df = pd.DataFrame(metadata)

display(metadata_df.head())


url = "https://jsonplaceholder.typicode.com/users"

response = requests.get(url)

api_df = pd.DataFrame(response.json())

display(api_df.head())

,customer_id,age,gender,region,education_level,employment_type,annual_income,loan_amount,loan_purpose,credit_score,repayment_history,transaction_count,spending_ratio,join_date,default_flag
0,1,NaN,Female,North,Primary,Salaried,1077610.09,664785.70,Car,700.8,11,461,56.36,2024-08-15,0
1,2,NaN,Female,East,Primary,Salaried,807240.03,564159.13,Business,687.7,10,364,56.32,2020-06-21,0
2,3,NaN,Other,West,Primary,Self-Employed,663601.61,NaN,Home,734.8,5,438,39.24,2020-12-19,0
3,4,56.0,Male,South,Graduate,Salaried,875676.45,40513.55,Car,574.6,5,300,26.34,2018-10-12,1
4,5,27.0,Other,South,Secondary,Salaried,459448.99,587944.74,Business,714.2,10,141,69.65,2025-08-31,1

   customer_id                email       city    state
0            1  customer1@gmail.com  Ahmedabad  Gujarat
1            2  customer2@gmail.com      Surat  Gujarat

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."

# Part - C

In [2]:
from ydata_profiling import ProfileReport

print("Dataset Information:",df.info())
print("Dataset Description:",df.describe())

profile = df.profile_report(title="Customer Credit Risk Dataset Report")
profile

C:\Users\Priyansh\AppData\Local\Temp\ipykernel_12856\3045549089.py:1: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        5000 non-null   int64
 1   age                4750 non-null   float64
 2   gender             4850 non-null   object
 3   region             5000 non-null   object
 4   education_level    5000 non-null   object
 5   employment_type    4750 non-null   object
 6   annual_income      4700 non-null   float64
 7   loan_amount        4800 non-null   float64
 8   loan_purpose       5000 non-null   object
 9   credit_score       4750 non-null   float64
 10  repayment_history  5000 non-null   int64
 11  transaction_count  5000 non-null   int64
 12  spending_ratio     5000 non-null   float64
 13  join_date          5000 non-null   object
 14  default_flag       5000 non-null   int64
dtypes: float64(5), int64(4), object(6)
memory usage: 586.1+ KB
Dataset Information: None
Dataset Description:        customer_id          age  annual_income   loan_amount  credit_score  \
count  5000.000000  4750.000000   4.700000e+03  4.800000e+03   4750.000000
mean   2500.500000    45.615158   7.709522e+05  4.055845e+05    680.275832
std    1443.520003    14.466293   6.386232e+05  2.377114e+05     69.466626
min       1.000000    21.000000   5.000000e+04  1.000000e+04    415.900000
25%    1250.750000    33.000000   5.008710e+05  2.261736e+05    632.525000
50%    2500.500000    45.000000   7.047853e+05  3.996157e+05    680.500000
75%    3750.250000    58.000000   9.152051e+05  5.736819e+05    728.175000
max    5000.000000    70.000000   7.577316e+06  1.340616e+06    850.000000

       repayment_history  transaction_count  spending_ratio  default_flag
count        5000.000000         5000.00000     5000.000000   5000.000000
mean            6.067800          251.89340       52.231730      0.310800
std             3.707769          142.31751       24.711715      0.462867
min             0.000000            5.00000       10.040000      0.000000
25%             3.000000          129.00000       30.800000      0.000000
50%             6.000000          252.00000       52.175000      0.000000
75%             9.000000          374.00000       73.850000      1.000000
max            12.000000          500.00000       94.990000      1.000000

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 15/15 [00:00<00:00, 166.68it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
from sklearn.impute import SimpleImputer
import numpy as np
from sklearn.impute import KNNImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

#Mean
mean_imputer = SimpleImputer(strategy="mean")
df_mean = df.copy()
df_mean[["age","annual_income"]] = mean_imputer.fit_transform(
    df_mean[["age","annual_income"]]
)

#Median
median_imputer = SimpleImputer(strategy="median")
df_median = df.copy()
df_median[["loan_amount","credit_score"]] = median_imputer.fit_transform(
    df_median[["loan_amount","credit_score"]]
)





#Random Sample Imputation
df_random = df.copy()
df_random["annual_income_missing"] = df_random["annual_income"].isnull().astype(int)

random_sample = df_random["annual_income"].dropna()

missing_index = df_random[df_random["annual_income"].isnull()].index

df_random.loc[missing_index, "annual_income"] = np.random.choice(random_sample,size=len(missing_index),replace=True)


#KNN Imputation
df_knn = df.copy()
knn = KNNImputer(n_neighbors=5)

cols = ["age","annual_income","loan_amount","credit_score"]

df_knn[cols] = knn.fit_transform(df_knn[cols])


#Mice Imputation
df_mice = df.copy()
mice = IterativeImputer(random_state=42)

cols = ["age","annual_income","loan_amount","credit_score"]

df_mice[cols] = mice.fit_transform(df_mice[cols])

#Most Frequent
df_mice["gender"] = df_mice["gender"].fillna(df_mice["gender"].mode()[0])

df_mice["employment_type"] = df_mice["employment_type"].fillna(df_mice["employment_type"].mode()[0])

print(df_mice.isnull().sum())

customer_id          0
age                  0
gender               0
region               0
education_level      0
employment_type      0
annual_income        0
loan_amount          0
loan_purpose         0
credit_score         0
repayment_history    0
transaction_count    0
spending_ratio       0
join_date            0
default_flag         0
dtype: int64

# Part - D Outlier Handling

In [5]:
from scipy import stats

z_scores = stats.zscore(df_mice["annual_income"])
df_mice = df_mice[abs(z_scores) < 3]
display("Z-score", df_mice.head())

# IQR method
Q1 = df_mice["loan_amount"].quantile(0.25)
Q3 = df_mice["loan_amount"].quantile(0.75)
IQR = Q3 - Q1
df_mice = df_mice[(df_mice["loan_amount"] >= Q1 - 1.5 * IQR) & (df_mice["loan_amount"] <= Q3 + 1.5 * IQR)]
display("IQR", df_mice.head())

# Percentile method
lower_percentile = df_mice["loan_amount"].quantile(0.01)
upper_percentile = df_mice["loan_amount"].quantile(0.99)
df_mice = df_mice[(df_mice["loan_amount"] >= lower_percentile) & (df_mice["loan_amount"] <= upper_percentile)]
display("Percentile", df_mice.head())

# Winsorization method
from scipy.stats.mstats import winsorize

df_mice["loan_amount"] = winsorize(df_mice["loan_amount"], limits=[0.01, 0.01])
display("Winsorization", df_mice.head())

'Z-score'

,customer_id,age,gender,region,education_level,employment_type,annual_income,loan_amount,loan_purpose,credit_score,repayment_history,transaction_count,spending_ratio,join_date,default_flag
0,1,45.294164,Female,North,Primary,Salaried,1077610.09,664785.70000,Car,700.8,11,461,56.36,2024-08-15,0
1,2,45.468088,Female,East,Primary,Salaried,807240.03,564159.13000,Business,687.7,10,364,56.32,2020-06-21,0
2,3,45.664050,Other,West,Primary,Self-Employed,663601.61,405072.14523,Home,734.8,5,438,39.24,2020-12-19,0
3,4,56.000000,Male,South,Graduate,Salaried,875676.45,40513.55000,Car,574.6,5,300,26.34,2018-10-12,1
4,5,27.000000,Other,South,Secondary,Salaried,459448.99,587944.74000,Business,714.2,10,141,69.65,2025-08-31,1

'IQR'

,customer_id,age,gender,region,education_level,employment_type,annual_income,loan_amount,loan_purpose,credit_score,repayment_history,transaction_count,spending_ratio,join_date,default_flag
0,1,45.294164,Female,North,Primary,Salaried,1077610.09,664785.70000,Car,700.8,11,461,56.36,2024-08-15,0
1,2,45.468088,Female,East,Primary,Salaried,807240.03,564159.13000,Business,687.7,10,364,56.32,2020-06-21,0
2,3,45.664050,Other,West,Primary,Self-Employed,663601.61,405072.14523,Home,734.8,5,438,39.24,2020-12-19,0
3,4,56.000000,Male,South,Graduate,Salaried,875676.45,40513.55000,Car,574.6,5,300,26.34,2018-10-12,1
4,5,27.000000,Other,South,Secondary,Salaried,459448.99,587944.74000,Business,714.2,10,141,69.65,2025-08-31,1

'Percentile'

,customer_id,age,gender,region,education_level,employment_type,annual_income,loan_amount,loan_purpose,credit_score,repayment_history,transaction_count,spending_ratio,join_date,default_flag
0,1,45.294164,Female,North,Primary,Salaried,1077610.09,664785.70000,Car,700.8,11,461,56.36,2024-08-15,0
1,2,45.468088,Female,East,Primary,Salaried,807240.03,564159.13000,Business,687.7,10,364,56.32,2020-06-21,0
2,3,45.664050,Other,West,Primary,Self-Employed,663601.61,405072.14523,Home,734.8,5,438,39.24,2020-12-19,0
3,4,56.000000,Male,South,Graduate,Salaried,875676.45,40513.55000,Car,574.6,5,300,26.34,2018-10-12,1
4,5,27.000000,Other,South,Secondary,Salaried,459448.99,587944.74000,Business,714.2,10,141,69.65,2025-08-31,1

'Winsorization'

,customer_id,age,gender,region,education_level,employment_type,annual_income,loan_amount,loan_purpose,credit_score,repayment_history,transaction_count,spending_ratio,join_date,default_flag
0,1,45.294164,Female,North,Primary,Salaried,1077610.09,664785.70000,Car,700.8,11,461,56.36,2024-08-15,0
1,2,45.468088,Female,East,Primary,Salaried,807240.03,564159.13000,Business,687.7,10,364,56.32,2020-06-21,0
2,3,45.664050,Other,West,Primary,Self-Employed,663601.61,405072.14523,Home,734.8,5,438,39.24,2020-12-19,0
3,4,56.000000,Male,South,Graduate,Salaried,875676.45,40513.55000,Car,574.6,5,300,26.34,2018-10-12,1
4,5,27.000000,Other,South,Secondary,Salaried,459448.99,587944.74000,Business,714.2,10,141,69.65,2025-08-31,1

# Part - E

In [6]:
df["join_date"] = pd.to_datetime(df["join_date"])

df["join_year"] = df["join_date"].dt.year
df["join_month"] = df["join_date"].dt.month
df["join_day"] = df["join_date"].dt.day
df["join_weekday"] = df["join_date"].dt.day_name()

df.head()

,customer_id,age,gender,region,education_level,employment_type,annual_income,loan_amount,loan_purpose,credit_score,repayment_history,transaction_count,spending_ratio,join_date,default_flag,join_year,join_month,join_day,join_weekday
0,1,NaN,Female,North,Primary,Salaried,1077610.09,664785.70,Car,700.8,11,461,56.36,2024-08-15,0,2024,8,15,Thursday
1,2,NaN,Female,East,Primary,Salaried,807240.03,564159.13,Business,687.7,10,364,56.32,2020-06-21,0,2020,6,21,Sunday
2,3,NaN,Other,West,Primary,Self-Employed,663601.61,NaN,Home,734.8,5,438,39.24,2020-12-19,0,2020,12,19,Saturday
3,4,56.0,Male,South,Graduate,Salaried,875676.45,40513.55,Car,574.6,5,300,26.34,2018-10-12,1,2018,10,12,Friday
4,5,27.0,Other,South,Secondary,Salaried,459448.99,587944.74,Business,714.2,10,141,69.65,2025-08-31,1,2025,8,31,Sunday

### Encoding Categorical Variables

In [ ]:
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder

# 1.Ordinal Encoding
encoder = OrdinalEncoder(categories=[["Primary","Secondary","Graduate","Post-Graduate"]])
df_mice["education_encoded"] = encoder.fit_transform(df_mice[["education_level"]])
display("Ordinal",df_mice[["education_level", "education_encoded"]].head())

# 2. Label Encoding 
df["high_credit"] = (df_mice["credit_score"] > 700).astype(int)
display("Label",df_mice[["credit_score", "high_credit"]].head())

# 3. One-Hot Encoding
ohe = OneHotEncoder(drop="first",sparse_output=False,handle_unknown="ignore")
encoded = ohe.fit_transform(df[["region", "loan_purpose"]])
encoded_df = pd.DataFrame(encoded,columns=ohe.get_feature_names_out(["region", "loan_purpose"]),index=df.index)
df = pd.concat([df, encoded_df], axis=1)
df.head()

'Ordinal'

  education_level  education_encoded
0         Primary                0.0
1         Primary                0.0
2         Primary                0.0
3        Graduate                2.0
4       Secondary                1.0

'Label'

   credit_score  high_credit
0         700.8            1
1         687.7            0
2         734.8            1
3         574.6            0
4         714.2            1

,customer_id,age,gender,region,education_level,employment_type,annual_income,loan_amount,loan_purpose,credit_score,...,join_weekday,education_encoded,high_credit,region_North,region_South,region_West,loan_purpose_Car,loan_purpose_Education,loan_purpose_Home,loan_purpose_Other
0,1,NaN,Female,North,Primary,Salaried,1077610.09,664785.70,Car,700.8,...,Thursday,0.0,1,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1,2,NaN,Female,East,Primary,Salaried,807240.03,564159.13,Business,687.7,...,Sunday,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,NaN,Other,West,Primary,Self-Employed,663601.61,NaN,Home,734.8,...,Saturday,0.0,1,0.0,0.0,1.0,0.0,0.0,1.0,0.0
3,4,56.0,Male,South,Graduate,Salaried,875676.45,40513.55,Car,574.6,...,Friday,2.0,0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
4,5,27.0,Other,South,Secondary,Salaried,459448.99,587944.74,Business,714.2,...,Sunday,1.0,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0

### Encoding Numerical Variables

In [ ]:
from sklearn.preprocessing import Binarizer
from sklearn.cluster import KMeans

# 1. Binning
df_mice["income_group"] = pd.cut(df_mice["annual_income"],bins=[0, 300000, 600000, 1000000, np.inf],labels=["Low","Medium","High","Very High"])
display("Binned", df_mice[["annual_income", "income_group"]].head(10))

# 2. Binerization
binarizer = Binarizer(threshold=700)
df_mice["credit_score_binary"] = binarizer.fit_transform(df_mice[["credit_score"]])

display("Binerized", df_mice[["credit_score", "credit_score_binary"]].head()) 

# 3. Quntile Binning
df_mice["income_quantile"] = pd.qcut(df_mice["annual_income"],q=4,labels=["Q1-Low","Q2","Q3","Q4-High"])
display("Quntile Binned", df_mice[["annual_income", "income_quantile"]].head(10))

# 4. K-Means Binning
income_data = df_mice[["annual_income"]].dropna()
kmeans = KMeans(n_clusters=4,random_state=42,n_init=10)
income_data["income_cluster"] = kmeans.fit_predict(income_data[["annual_income"]])
df_mice.loc[income_data.index, "income_cluster"] = (income_data["income_cluster"])

display("K-Means Binned", df_mice[["annual_income", "income_cluster"]].head(10))

'Binned'

    annual_income income_group
0      1077610.09    Very High
1       807240.03         High
2       663601.61         High
3       875676.45         High
4       459448.99       Medium
5       939802.92         High
7      1102267.96    Very High
8       971015.59         High
9       554723.96       Medium
11      501277.36       Medium

'Binerized'

   credit_score  credit_score_binary
0         700.8                  1.0
1         687.7                  0.0
2         734.8                  1.0
3         574.6                  0.0
4         714.2                  1.0

'Quntile Binned'

    annual_income income_quantile
0      1077610.09         Q4-High
1       807240.03              Q3
2       663601.61              Q2
3       875676.45              Q3
4       459448.99          Q1-Low
5       939802.92         Q4-High
7      1102267.96         Q4-High
8       971015.59         Q4-High
9       554723.96              Q2
11      501277.36          Q1-Low

    annual_income  income_cluster
0      1077610.09             2.0
1       807240.03             0.0
2       663601.61             1.0
3       875676.45             0.0
4       459448.99             1.0
5       939802.92             0.0
7      1102267.96             2.0
8       971015.59             2.0
9       554723.96             1.0
11      501277.36             1.0

# Part - F

In [13]:
from sklearn.preprocessing import StandardScaler, Normalizer, MinMaxScaler,MaxAbsScaler,RobustScaler
num_cols = [
    "age",
    "annual_income",
    "loan_amount",
    "credit_score",
    "repayment_history",
    "transaction_count",
    "spending_ratio"
]

# 1. Z-Score Scaling
standard_scaler = StandardScaler()
df_standard = df_mice.copy()
df_standard[num_cols] = standard_scaler.fit_transform(df_standard[num_cols])
display("Z-Score", df_standard[num_cols].head())

#2. Normalization
normalizer = Normalizer(norm="l2")
df_normalized = df_mice.copy()
df_normalized[num_cols] = normalizer.fit_transform(df_normalized[num_cols])
display("Normalization", df_normalized[num_cols].head())

#3.Min-Max Scaling

minmax_scaler = MinMaxScaler()
df_minmax = df_mice.copy()

df_minmax[num_cols] = minmax_scaler.fit_transform(df_minmax[num_cols])
display("Min-Max", df_minmax[num_cols].head())

#4. Max-Abs Scaling

maxabs_scaler = MaxAbsScaler()
df_maxabs = df_mice.copy()

df_maxabs[num_cols] = maxabs_scaler.fit_transform(df_maxabs[num_cols])
display("Max-Abs", df_maxabs[num_cols].head())

#5. Robust Scaling

robust_scaler = RobustScaler()
df_robust = df_mice.copy()

df_robust[num_cols] = robust_scaler.fit_transform(df_robust[num_cols])
display("Robust", df_robust[num_cols].head())

'Z-Score'

,age,annual_income,loan_amount,credit_score,repayment_history,transaction_count,spending_ratio
0,-0.024515,1.342015,1.274605,0.299999,1.333265,1.476680,0.166699
1,-0.012158,0.380542,0.808122,0.106367,1.062742,0.794265,0.165079
2,0.001765,-0.130257,0.070629,0.802557,-0.289875,1.314870,-0.526924
3,0.736124,0.623911,-1.619385,-1.565375,-0.289875,0.344013,-1.049572
4,-1.324298,-0.856252,0.918387,0.498066,1.062742,-0.774584,0.705149

'Normalization'

,age,annual_income,loan_amount,credit_score,repayment_history,transaction_count,spending_ratio
0,0.000036,0.851079,0.525037,0.000553,0.000009,0.000364,0.000045
1,0.000046,0.819665,0.572843,0.000698,0.000010,0.000370,0.000057
2,0.000059,0.853546,0.521017,0.000945,0.000006,0.000563,0.000050
3,0.000064,0.998931,0.046216,0.000655,0.000006,0.000342,0.000030
4,0.000036,0.615741,0.787948,0.000957,0.000013,0.000189,0.000093

'Min-Max'

,age,annual_income,loan_amount,credit_score,repayment_history,transaction_count,spending_ratio
0,0.495799,0.671278,0.781613,0.656300,0.916667,0.921212,0.545262
1,0.499349,0.494661,0.661496,0.626123,0.833333,0.725253,0.544791
2,0.503348,0.400830,0.471595,0.734623,0.416667,0.874747,0.343732
3,0.714286,0.539367,0.036424,0.365584,0.416667,0.595960,0.191878
4,0.122449,0.267469,0.689889,0.687169,0.833333,0.274747,0.701707

'Max-Abs'

,age,annual_income,loan_amount,credit_score,repayment_history,transaction_count,spending_ratio
0,0.647059,0.681675,0.784189,0.824471,0.916667,0.922,0.593326
1,0.649544,0.510644,0.665489,0.809059,0.833333,0.728,0.592905
2,0.652344,0.419782,0.477828,0.864471,0.416667,0.876,0.413096
3,0.800000,0.553936,0.047790,0.676000,0.416667,0.600,0.277292
4,0.385714,0.290639,0.693547,0.840235,0.833333,0.282,0.733235

'Robust'

,age,annual_income,loan_amount,credit_score,repayment_history,transaction_count,spending_ratio
0,-0.014992,0.937509,0.817229,0.230197,0.833333,0.857143,0.096722
1,-0.007430,0.225331,0.503184,0.083171,0.666667,0.461224,0.095792
2,0.001090,-0.153025,0.006690,0.611790,-0.166667,0.763265,-0.301325
3,0.450479,0.405598,-1.131060,-1.186189,-0.166667,0.200000,-0.601256
4,-0.810390,-0.690780,0.577416,0.380589,0.666667,-0.448980,0.405720

# Part - G

In [14]:
from sklearn.preprocessing import FunctionTransformer,PowerTransformer,StandardScaler,MinMaxScaler
from sklearn.compose import ColumnTransformer

# Log Transformation
log_transformer = FunctionTransformer(np.log1p)

df_mice["income_log"] = log_transformer.transform(df_mice[["annual_income"]])

# Reciprocal Transformation
reciprocal_transformer = FunctionTransformer(lambda x: 1 / (x + 1e-9))

df_mice["loan_reciprocal"] = reciprocal_transformer.transform(df_mice[["loan_amount"]])

# Square Root Transformation
sqrt_transformer = FunctionTransformer(np.sqrt)

df_mice["transaction_sqrt"] = sqrt_transformer.transform(df_mice[["transaction_count"]])

# Box-Cox
boxcox = PowerTransformer(method="box-cox",standardize=False)

df_mice["income_boxcox"] = boxcox.fit_transform(df_mice[["annual_income"]]).ravel()

# Yeo-Johnson
yeojohnson = PowerTransformer(method="yeo-johnson",standardize=False)

df_mice["loan_yeojohnson"] = yeojohnson.fit_transform(
df_mice[["loan_amount"]]).ravel()


preprocessor = ColumnTransformer(transformers=[("income_scaling",StandardScaler(),["annual_income"]),
        ("loan_scaling",MinMaxScaler(),["loan_amount"]),
        ("transaction_log",FunctionTransformer(np.log1p),["transaction_count"])],
    remainder="passthrough")

transformed_data = preprocessor.fit_transform(df_mice)



df_mice["debt_to_income_ratio"] = (df_mice["loan_amount"] /df_mice["annual_income"])
df_mice["avg_monthly_transactions"] = (df_mice["transaction_count"] / 6)
df_mice["spending_to_income_ratio"] = (df_mice["spending_ratio"] / 100)


display(df_mice[["annual_income","income_log","income_boxcox","loan_amount","loan_reciprocal","loan_yeojohnson","transaction_count","transaction_sqrt","debt_to_income_ratio","avg_monthly_transactions","spending_to_income_ratio"]].head())

,annual_income,income_log,income_boxcox,loan_amount,loan_reciprocal,loan_yeojohnson,transaction_count,transaction_sqrt,debt_to_income_ratio,avg_monthly_transactions,spending_to_income_ratio
0,1077610.09,13.890257,472523.154420,664785.70000,0.000002,43041.981364,461,21.470911,0.616907,76.833333,0.5636
1,807240.03,13.601378,360585.798739,564159.13000,0.000002,37888.254640,364,19.078784,0.698874,60.666667,0.5632
2,663601.61,13.405439,300171.636283,405072.14523,0.000002,29289.456512,438,20.928450,0.610415,73.000000,0.3924
3,875676.45,13.682753,389119.977563,40513.55000,0.000025,4893.922395,300,17.320508,0.046265,50.000000,0.2634
4,459448.99,13.037785,212783.228676,587944.74000,0.000002,39123.779031,141,11.874342,1.279674,23.500000,0.6965

In [16]:
df_mice.to_csv("final_cleaned_dataset.csv",index=False)
print("Final Info", df_mice.info())

<class 'pandas.core.frame.DataFrame'>
Index: 4781 entries, 0 to 4999
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               4781 non-null   int64
 1   age                       4781 non-null   float64
 2   gender                    4781 non-null   object
 3   region                    4781 non-null   object
 4   education_level           4781 non-null   object
 5   employment_type           4781 non-null   object
 6   annual_income             4781 non-null   float64
 7   loan_amount               4781 non-null   float64
 8   loan_purpose              4781 non-null   object
 9   credit_score              4781 non-null   float64
 10  repayment_history         4781 non-null   int64
 11  transaction_count         4781 non-null   int64
 12  spending_ratio            4781 non-null   float64
 13  join_date                 4781 non-null   object
 14  default_flag              4781 non-null   int64
 15  income_group              4781 non-null   category
 16  credit_score_binary       4781 non-null   float64
 17  income_quantile           4781 non-null   category
 18  income_cluster            4781 non-null   float64
 19  income_log                4781 non-null   float64
 20  loan_reciprocal           4781 non-null   float64
 21  transaction_sqrt          4781 non-null   float64
 22  income_boxcox             4781 non-null   float64
 23  loan_yeojohnson           4781 non-null   float64
 24  debt_to_income_ratio      4781 non-null   float64
 25  avg_monthly_transactions  4781 non-null   float64
 26  spending_to_income_ratio  4781 non-null   float64
dtypes: category(2), float64(15), int64(4), object(6)
memory usage: 1.1+ MB
Final Info None

========== FINAL DELIVERABLE REPORT ==========

1. Missing Value Strategies:
- Numerical missing values were handled using MICE (Iterative Imputer).
- MICE uses information from other variables to estimate missing values.
- This preserves the dataset better than simply dropping missing rows.

2. Outlier Handling:
- Outliers were detected using Z-Score, IQR, Percentile and Winsorization
  techniques during the preprocessing stage.
- The appropriate outlier treatment was selected based on the variable
  distribution.

3. Encoding:
- Ordinal Encoding was applied to education_level.
- Label/Binary Encoding was applied to binary categorical features.
- One-Hot Encoding was applied to region and loan_purpose.
- Numerical features were encoded/binned where required.

4. Scaling and Transformations:
- Feature scaling techniques were applied to numerical variables.
- Standardization, Normalization, Min-Max, MaxAbs and Robust Scaling
  were evaluated.
- Log, Reciprocal and Square Root transformations were used to reduce
  skewness where appropriate.

5. Feature Engineering:
- Debt-to-Income Ratio was created.
- Average Monthly Transactions was created.
- Spending-to-Income Ratio was created.
- Date features such as Year, Month, Day and Weekday were extracted.

6. Final Dataset:
- The final processed dataset is stored as df_mice.
- Missing values were handled using MICE.
- The dataset is cleaned, transformed and prepared for Machine Learning.